services:
  ohlc-db:
    image: timescale/timescaledb-ha:pg16-ts2.23-all
    container_name: ohlc-db
    environment:
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ohlc_store
      - TS_TUNE=TRUE
    ports:
      - "54329:5432"
    volumes:
      - ohlc_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ohlc_store"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  ohlc_data: {}
